// <auto-generated />
using System;
using ApiTestePraticoDesenvolvedor.Infra.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTestePraticoDesenvolvedor.Infra.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240608035255_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTestePraticoDesenvolvedor.Domain.Entities.ContaEntity", b =>
                {
                    b.Property<Guid>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasAtrasados")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ValorCorrigido")
                        .HasColumnType("float");

                    b.Property<double>("ValorOriginal")
                        .HasColumnType("float");

                    b.HasKey("IdConta")
                        .HasName("ID_CONTA");

                    b.ToTable("CONTA_DATABASE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
